version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - list_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  task_list:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: task_list
    depends_on:
      - db
      - redis
    env_file: .env
    ports:
      - "8080:8080"


volumes:
  list_postgres_data:
